---
title: "Task 1"
author: "Santiago Nule"
date: "10/28/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(COVID19)
library(tidyverse)
library(readr)
library(lubridate)
```


```{r}
covid19("US", level = 2) %>%
  rename(state_name = administrative_area_level_2 ) %>% 
  select(-c("administrative_area_level_1","administrative_area_level_3","latitude","longitude","currency", "administrative_area_level_1")) %>% 
  arrange(state_name) %>% 
  relocate("state_name", "date", "confirmed", "tests")-> easy_covid_df

easy_covid_df
```

1.Get the average for confirmed cases 14 days prior to 1st stay home restriction.
2. Get the average for confimed cases from 15 to 30 days after stay at home restrictions are first imposed. 
3. Find the difference for each state
4. Adjust to population by state
5. plot


```{r}
#Two columns - one for restriction 1 and one for restriction level 2. Values would be a, b and none in each. The a is the before restriction group (first date - )and the b is the after restriction group (firstdate + 30  ) and then none for dates not in the cohort.
#Then summarize the mean for each cohort in a group by state, restriction level, cohort.

easy_covid_df %>% 
  group_by(state_name, stay_home_restrictions) %>% 
  select(c("state_name", "date","confirmed","date", "population", "stay_home_restrictions" )) %>% 
  mutate(first_date0 = min(date),
            dateplus30 = first_date0+days(30)) %>% 
  ungroup() %>% 
  group_by(state_name) %>% 
  # mutate(cohort1 = stay_home_restrictions ==1 ),  
  #        cohort2= case_when()) %>%  
  mutate(cohorta= (date<=first_date0 & date>(first_date0-days(14))),
         cohortb = (date<dateplus30 & date>=(dateplus30-days(14))))%>%
  relocate(cohorta, cohortb, date, first_date0, dateplus30) %>% 
  arrange(state_name) %>% 
  view()
  

```
```{r}
easy_covid_df %>% 
  group_by(state_name, stay_home_restrictions) %>% 
  select(c("state_name", "date","confirmed","date", "population" )) %>% 
  mutate(first_date0 = min(date),
            dateplus30 = first_date0+days(30)) %>% 
  distinct(first_date0)
```

```{r}
easy_covid_df %>% 
  select(c("state_name", "date","confirmed","date", "population", "stay_home_restrictions" )) %>% 
  group_by(state_name, stay_home_restrictions) %>% 
  mutate(first_date0 = min(date),
            dateplus30 = first_date0+days(30)) %>% 
  ungroup() %>% 
  group_by(state_name) %>% 
   mutate(cohort1 = case_when(stay_home_restrictions <1 & date<=first_date0 & date>(first_date0-days(14))~"a",
                              stay_home_restrictions ==1 & date<=dateplus30 & date>=(dateplus30-days(14))~"b",
                             stay_home_restrictions == 1 & date>first_date0 & date<(dateplus30-days(14))| date<(first_date0-days(14))| date>(dateplus30) | stay_home_restrictions != 1 ~"None"),
         cohort2= case_when(stay_home_restrictions <2 & date<=first_date0 & date>(first_date0-days(14))~"a",
                              stay_home_restrictions ==2 & date<=dateplus30 & date>=(dateplus30-days(14))~"b",
                             stay_home_restrictions == 2 & date>first_date0 & date<(dateplus30-days(14))| date<(first_date0-days(14))| date>(dateplus30) | stay_home_restrictions != 2 ~"None")) %>%  
  relocate(state_name, stay_home_restrictions, cohort1, cohort2, date, first_date0, dateplus30) %>% 
  view()
```


```{r}
easy_covid_df %>% 
  select(c("state_name", "date","confirmed","date", "population", "stay_home_restrictions" )) %>%
  filter(!is.na(stay_home_restrictions) ) %>% 
  group_by(state_name, stay_home_restrictions) %>% 
  summarize(first_date0 = min(date))-> day1and2

day1and2 %>% 
  pivot_wider(names_from = "stay_home_restrictions", values_from = "first_date0", names_prefix= "R-")->day1and2

day1and2

```

```{r}
easy_covid_df %>% 
  select(c("state_name", "date","confirmed","date", "population", "stay_home_restrictions" )) %>%
  left_join(day1and2, by = c("state_name")) %>%
  filter(date<mdy("05/01/20") & date> mdy("03/15/20")) %>% 
  ggplot(aes(x=date, y= stay_home_restrictions, color = state_name))+
  geom_line()+
  facet_wrap(~state_name)+
  coord_flip()+
  theme(legend.position= "none")
  
  
```
```{r}
easy_covid_df %>% 
  select(c("state_name", "date","confirmed","date", "population", "stay_home_restrictions" )) %>%
  left_join(day1and2, by = c("state_name")) %>%
  filter(date<mdy("05/01/20") & date> mdy("03/15/20")) %>% 
  ggplot(aes(x=date, y= stay_home_restrictions, color = state_name))+
  geom_line()+
  facet_wrap(~state_name)+
  theme(legend.position= "none")
  
```



```{r}
ungroup() %>% 
  group_by(state_name) %>% 
  #pivot_wider( names_from = stay_home_restrictions, values_from = first_date0, names_prefix = "R-") %>% 
  view()
   mutate(cohort1 = case_when(stay_home_restrictions <1 & date<=first_date0 & date>(first_date0-days(14))~"a",
                              stay_home_restrictions ==1 & date<=dateplus30 & date>=(dateplus30-days(14))~"b",
                             TRUE ~"None"),
         cohort2= case_when(stay_home_restrictions <2 & date<=first_date0 & date>(first_date0-days(14))~"a",
                              stay_home_restrictions ==2 & date<=dateplus30 & date>=(dateplus30-days(14))~"b",
                             TRUE ~"None")) %>%  
  relocate(state_name, stay_home_restrictions, cohort1, cohort2, date, first_date0, dateplus30) %>% 
  view()
```


```{r}
easy_covid_df %>% 
  group_by(state_name, stay_home_restrictions) %>% 
  summarise(first_date0 = min(date),
            dateplus30 = first_date0+days(30)) %>% 
  #distinct(first_date0, .keep_all = TRUE) %>% 
  filter(!is.na(stay_home_restrictions)&(!stay_home_restrictions==0)) %>% 
  arrange(first_date0) %>% 
  # group_by(first_date0) %>% 
  # distinct(state_name, .keep_all=TRUE) %>% 
  group_by(state_name) ->first_date_stayh_orders2
  #filter(date == min(date))

first_date_stayh_orders2 %>% 
  arrange(state_name)

# #after_30_change <- function(easy_covid_df) {
#   if {easy_covid_df$date == 


# first_date_stayh_orders2 %>% 
#   filter(date == first_date0 | date == first_date0+days(30)) %>% 
#   arrange(state_name)
# first_date_stayh_orders2 %>% 
#   mutate(date = date + days(30))-> date_of_30
# 
# easy_covid_df
# 
# easy_covid_df %>% 
#    filter(date %in% first_date_stayh_orders)-> date_of_30
```

